# File: .github/workflows/workflow.yml

on: [push]
    workflow_dispatch:

name: Run Azure Login With a Service Principal Secret

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show
          az account set -s 7c28be4b-1ee7-4c4f-b650-72b08e5eed61
          az vm list -o table
          az group create dvtest3 --location eastus
          az vm create --name test-vm4 -g dvtest3
          az vm list -o table
          az account show
